branches:
  only:
    - dev
matrix:
  include:
    - stage: "phpunit"
      language: php
      php: '7.1'
      os: linux
      before_script:
        - cp .env.travis .env
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - phpenv config-rm xdebug.ini
      script:
        - vendor/bin/phpunit
    - stage: "jest"
      language: node_js
      os: linux
      node_js: '8'
      cache:
          directories:  
            - node_modules
      install:
        - yarn install
      script:
        - yarn test:unit

